### ISSUE TITLE
[ReactUI] GetPopUpAPI.php - when spectator need to return stats.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#133]
Example curl:
`
curl 'http://127.0.0.1:5173/api/live/GetPopupAPI.php?gameName=464517&playerID=3&authKey=&popupType=myStatsPopup&index=0' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0' -H 'Accept: */*' -H 'Accept-Language: en-GB,en-US;q=0.7,en;q=0.3' -H 'Accept-Encoding: gzip, deflate, br' -H 'Referer: http://127.0.0.1:5173/?gameName=464517&playerID=3' -H 'Connection: keep-alive' -H 'Cookie: PHPSESSID=oq0f9o54ggha31tujcse25p62c' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache'`

Response:
<b>Warning</b>: file_get_contents(./Games/464517/p3Deck.txt): Failed to open stream: No such file or directory in <b>/opt/lampp/htdocs/game/GetPopupAPI.php</b> on line <b>74</b><br />

https://github.com/Talishar/Talishar-FE/issues/36

**Comment by OotTheMonk** [comment]
The error is because there's no stats for player 3. Right now spectators fairly arbitrarily see the stats for player 1. We should decide what we want spectators and players to be able to see about stats. We could either show nothing, show player 1 stats like currently (seems silly), or allow them to toggle between both. But if the latter, we should probably let player 1 and player 2 toggle between each other's stats too. Either way I don't think development is needed for this, since you can get player 1 and player 2's stats by requesting the stats for that player. Can change the variable/API if that is needed though. (for example if we want to arbitarily show player 1's stats for player 3, I can make it return player 1's stats when player 3 is passed).
