### ISSUE TITLE
[Bug] - Fractal replication not seeing base attack modifiers

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#230]
664088 interaction: Transmorgify (y) into Promise of Plenty (b) into Fractal Replication.

Expected Fractal to get 7 power from Promise of Plenty because Transmorgify gave Promise base 7 power. But Fractal got 1 power instead

**Comment by LaustinSpayce** [comment]
I don't think this is a bug as setting the base attack to a different value is not on the card itself:

https://fabtcg.com/articles/quick-questions-everfest-rules-reprise/

Need to check with a judge though.

**Comment by ZacharyCauchi** [comment]
The example in the release notes has phantasmify, which increases the attack of the following attack action and would not effect the fractal replication.

However, transmogrify specifically modifies the next attack action card's "base attack". Because of this difference in wording, fractal replication should have its attack power affected by transmogrify.

I encountered this bug myself in a game on talishar recently.

**Comment by ZacharyCauchi** [comment]
@LaustinSpayce 

The example in the release notes mentions phantasmify, which increases the attack of the following attack action and would not effect the fractal replication.
 
However, transmogrify specifically overrides the next attack action card's "base attack" (as opposed to increasing the cards attack). Because of this difference in wording, fractal replication should have its attack power affected by transmogrify.

I encountered this bug myself in a game on talishar recently.

**Comment by PvtVoid** [comment]
Seems like a critical bug, there's a dozen of bug reports on it. I tried to fix it, without sucess.

https://discord.com/channels/865412150125789214/865423689976774656/1187159011389354004
https://discord.com/channels/865412150125789214/865423689976774656/1182454142111850526
https://discord.com/channels/865412150125789214/865423689976774656/1074878292575932436
https://discord.com/channels/865412150125789214/865423689976774656/1031655685198458890
https://discord.com/channels/865412150125789214/865423689976774656/1031475536221966346
https://discord.com/channels/865412150125789214/865423689976774656/1024198517813682187
https://discord.com/channels/865412150125789214/865423689976774656/1014177794378436609
etc....

**Comment by PvtVoid** [comment]
Fixed with https://github.com/Talishar/Talishar/pull/738/commits/19a87f6ee44cf08b655c92ed463644cca53f41fc
