### ISSUE TITLE
React FE cannot get Favorite Decks:

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#275]
calling `GetFavoriteDecks.php` :

Getfavoritedecks.php:
```
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function SetHeaders() in /var/www/html/game/APIs/GetFavoriteDecks.php:8
Stack trace:
#0 {main}
  thrown in <b>/var/www/html/game/APIs/GetFavoriteDecks.php</b> on line <b>8</b><br />
  ```
I fixed that - it's in a PR and now have:
```
<br />
<b>Fatal error</b>:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /var/www/html/game/APIs/GetFavoriteDecks.php:21
Stack trace:
#0 {main}
  thrown in <b>/var/www/html/game/APIs/GetFavoriteDecks.php</b> on line <b>21</b><br />
```

**Comment by OotTheMonk** [comment]
Fixed in a collection of commits this morning, was related to the other issue with an error about the user ID.
![image](https://user-images.githubusercontent.com/77394768/218322038-69cedfe8-4eb6-4f3d-984f-c25d62167b43.png)

Also added a postman test:
![image](https://user-images.githubusercontent.com/77394768/218322070-9b0684c8-54e0-4577-80b8-658d617c94fb.png)
