### ISSUE TITLE
React-FE With multiples of a permanent, we need toggling priority gems on one, to toggle gems on all.

### ISSUE THREAD

**Issue by LaustinSpayce** [Talishar/Talishar#296]
<img width="328" alt="image" src="https://user-images.githubusercontent.com/5060535/219684629-66c2436b-2f4d-4efc-a4a4-5a371db05e61.png">

One copper token has the gem on, the other doesn't. I think people in general want:

- All to have gems
- None to have gems
- None except for the very last one (for soul shackle etc)

So when toggling gems I think we need it to realise there are multiple and adjust the case? I'm not sure how it's handled on the legacy FE.

**Comment by LaustinSpayce** [comment]
I don't know why you transferred the BE should toggle gems for all when I toggle the gem for one.

**Comment by LaustinSpayce** [comment]
The reason this should be done on the BE is, in an example with 5 permanents. If I were to loop the gem status on the FE, if there were a stack of 5 permanents, there would be 5 requests to toggle the gem status per click. It gets quite spammy quite quickly if we were to do that.

**Comment by OotTheMonk** [comment]
When the items all have the same gem status, they stack nicely:
![image](https://user-images.githubusercontent.com/77394768/219958858-5094f33b-7bde-4f20-9727-67303ad9b9a3.png)

Once you toggle one, it splits off:
![image](https://user-images.githubusercontent.com/77394768/219958894-8d05a8b8-5dfc-470e-9dfe-8f8b36b6af29.png)

When you toggle the other one, it combines with the split off one again:
![image](https://user-images.githubusercontent.com/77394768/219959065-ac109be6-af2e-4aa9-bab8-eae255e74272.png)

The core of this issue is that we use deepequal to make sure the permanents are actually the same, and therefore should be stacked. If they're not the same (for example, one is frozen), then you _want_ them to be split off. This needs to be solved on the BE by cloning the gem value of the first stacked item with all the others.

**Comment by LaustinSpayce** [comment]
The most important thing for the stacking is, like, aether ash wings etc. dragons that have already attacked are in a separate pile to the ones yet to attack.

**Comment by OotTheMonk** [comment]
Fixed in revision 6c3c120d

Fixed by creating tileable map to clone gem value of the first tileable to the rest of them. That way the deep copy will work as expected. The first tile of a type is the one that controls the gem by convention.

![image](https://user-images.githubusercontent.com/77394768/219962033-d33e69f0-4fef-42e6-9c04-0a49a63ab59f.png)

Fix fully on BE; no additional FE changes needed. Closing issue.
