### ISSUE TITLE
908887 - [QoL] Change the border color on effects based on the owner of the effect (Example in comment)

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#371]
It would help with clarity and look cleaner if those 4 Seek&Destroy when reduced (only 2 showing 2 for Opp + Yours instead of 4) and could be colour coded so we know there's a "bad" one and a "good" one.
![image](https://user-images.githubusercontent.com/26232486/224533247-ae4df77a-9e8f-44c1-9d9d-925d3e2eff3f.png)

**Comment by OotTheMonk** [comment]
I fixed the color. I had to remove the deduplication because it was causing an issue where if you played two of the same card (for example like in this same screenshot), it was deduplicating those as well, so many players thought their card didn't do anything. We might try to improve that by deduplicating on the whole effect ID instead of the base ID, but that could cause issues with ones that have parameters. It's something we might have to look into with the new UI.

I did fix the color, though.
![image](https://user-images.githubusercontent.com/77394768/224548117-8e0934b9-6bcb-4fc0-9a33-e7c1e25069bb.png)
