### ISSUE TITLE
Multiple X-cost card create a problem and overwrite $CS_DynCost variable. Mostly affect X-cost action that can be played at instant speed 

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#50]
- Ice Eternal
- Beacon of Victory
- Sonata
- Spark of Genius
- Imposing Visage
https://discord.com/channels/865412150125789214/865423689976774656/1019216325115133992

**Comment by OotTheMonk** [comment]
I'm pretty sure this got fixed when I reworked the layer code to start encoding stuff into the layer itself once the layer is creating instead of trying to persist through the class state which was prone to being overwritten. If you're still seeing this, feel free to submit a bug report.
![image](https://user-images.githubusercontent.com/77394768/228697246-bd78e1f9-4dbf-404a-97e9-89fac2d425f1.png)
