### ISSUE TITLE
[2691979] - The combat chain show that I am attacking for -1, it should never go below 0

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#572]
<img width="957" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/e1f245a7-e995-4a8a-853f-c5761e8d1d77">

**Comment by OotTheMonk** [comment]
If the attack resolves, it will round it to 0 as per the rules. This visual reminder is intended, because you might play a reaction to buff it up. If we truncate the visual reminder to be 0 you might be surprised when you buff it by +3 and it only goes to 2. Closing as will not be fixed as this is a design decision.
