### ISSUE TITLE
[2709468] - Highlighting the choosen card for "Name a card" effect would improve those interactions

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#579]
I understand that it cannot be done with the pitch, but it can be done by highlighting important info in the chat. Like we highlight the manual mode, etc....
<img width="1280" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/027dc0b9-f635-4ae0-a77f-c3bcf349e23b">

**Comment by KuKetto** [comment]
All I could think of is to include bolding directly to the logging as `"<b>{0}</b> was chosen."` This works. I'm sure there is a better solution  and I think it should be better to have a function that looks up for the `cardID` based on `cardName` anyway. 

![Screenshot from 2023-09-20 10-16-48](https://github.com/Talishar/Talishar/assets/39841262/537fdb23-83a9-4774-8416-91633dccff37)

Like how `function GeneratedCardName($cardID)` operates, just reversed. Then these selections could be logged with the actual card, so you can hoover on them and see which card actually was selected. When having multiple cards (because of the multiple pitch colors) it could just return the first found / red variant to log. On the other hand this sounds a bit janky and complex, this would take a while.

@OotTheMonk Censor was implemented by you, what do you think?

**Comment by PvtVoid** [comment]
I think bolding the name is already a great idea! It will improve the readability and I didn't think about it. The option I had in mind highlighted the whole message more. If you can find the code for the manual mode you should be able to inspire yourself of it. 

I would be happy with bold or highlight
<img width="142" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/d6bbf4d4-c41f-4c92-aa70-ed037e6e663c">

**Comment by KuKetto** [comment]
Yeah there is a highlight option in logging. One with actual highlight and one with just different text color than regular logging.
![image](https://github.com/Talishar/Talishar/assets/39841262/c3b0abff-c3b3-42b1-9e89-c9fac1f7c79f)
Which one did you think of? The bottom one right?

**Comment by OotTheMonk** [comment]
Personally I strongly prefer just the bold, the one from manual mode is intentionally VERY LOUD to indicate that something other than the game engine changed something about the game state (ie, a manual player change)

**Comment by OotTheMonk** [comment]
Another option if we want it to be louder, is in the engine there is the capability for an Ok-only acknowledgement popup, for example with Sonic Boom:
![image](https://github.com/Talishar/Talishar/assets/77394768/3920c649-6b7d-44f8-8454-8e84990f3e9d)

I think we should go less loud first and then make it louder if there's still confusion with the card effect.

**Comment by PvtVoid** [comment]
> Personally I strongly prefer just the bold, the one from manual mode is intentionally VERY LOUD to indicate that something other than the game engine changed something about the game state (ie, a manual player change)

Push the fix for the bold https://github.com/Talishar/Talishar/pull/636/commits/bd1209cdbdc913e10a6f6ba6c202cdd1e194964f
<img width="117" alt="image" src="https://github.com/Talishar/Talishar/assets/26232486/4601cee6-82de-48c5-9a39-82b17f832ab8">
