### ISSUE TITLE
[4171802] - Instant cards lose card cost when other instants cards are on the stack resolving at instant

### ISSUE THREAD

**Issue by PvtVoid** [Talishar/Talishar#739]

**Comment by OotTheMonk** [comment]
I tried pulling this one. The issue was the ability activation was on the stack, but for some reason the process of paying for it was not completed before the prism player was given the chance to respond. So the process of paying for the genesis went after the process of paying for the ability, which gave the illusion of the genesis cost going away. In reality the genesis payment was just getting tacked on the end.

Unfortunately the issue has already occurred by the time of where the bug report happened. I tried rolling it back to the beginning of the turn, but was unable to replicate the issue. I tried multiple lines to try to reproduce. It's possible this got fixed in one of the many updates recently. I am closing this for now until we can get another report of the issue occurring.

**Comment by PvtVoid** [comment]
Another report: 4397053 - https://discord.com/channels/865412150125789214/865423689976774656/1206815162150158396

**Comment by PvtVoid** [comment]
4399622 - https://discord.com/channels/865412150125789214/865423689976774656/1206878910294261820

**Comment by PvtVoid** [comment]
@OotTheMonk found the bug. Fixed with 306a0b128d5d05fb9e6919227f1c773bd304daca. 

You fix 723635a30df06d3835d32b06563fb027fa6b2927 created that bug. I'm not sure what it does, but I reverted it for now
