### ISSUE TITLE
Deathly wail is making runechants attacking arclight sentinel

### ISSUE THREAD

**Issue by OotTheMonk** [Talishar/Talishar#812]
Game id: 4811687
https://discord.com/channels/865412150125789214/865423689976774656/1215466019879911444
https://discord.com/channels/865412150125789214/865423689976774656/1216083938385334332

**Comment by OotTheMonk** [comment]
Currently waiting for ruling from the judges on how this should work

**Comment by PvtVoid** [comment]
1.7.5. An activated ability can only be activated when it is functional. A resolution or static ability only
generates its effects when it is functional. An ability is functional when its source is public and in the
arena; otherwise, it is non-functional.

Card on the stack are not active as the stack is not in the arena. The attack never resolves past the layer step. So if the card has not resolved it's text is not active.

**Comment by PvtVoid** [comment]
Fixed with c6bfacafcc2f282330f0bde983c2840e64b15520
